[package]
authors = ["Hyundeok Park <p.hyundeok76@gmail.com>"]
name = "lotto-6-45"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["debug"] }
itertools = "0.14.0"
rand = "0.9.2"
